name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
